os: osx
language: node_js
node_js: '10'
addons:
  homebrew:
    packages:
      - rpm

cache:
  directories:
    - node_modules
    - "$HOME/.cache/electron"
    - "$HOME/.cache/electron-builder"

jobs:
  include:
    - stage: prepare
      name: "Run BurstJS Tests"
      script: './scripts/ci/test-burstjs.sh'
    - # parallel run
      name: "Run Angular Tests"
      script: './scripts/ci/test-ng.sh'
    - # parallel run
      name: "Build App"
      script: './scripts/ci/build-electron.sh'
    - stage: deploy
      name: "Build and Deploy Desktop App"
      script: './scripts/ci/release-desktop.sh --publish'
    - stage: force-deploy
      name: "Forced Build and Deploy Desktop App"
      script: './scripts/ci/release-desktop.sh --publish'
    - stage: nightly-release
      name: "Nightly Release of Desktop App"
      script: './scripts/ci/nightly-desktop.sh'

stages:
  - prepare
  - name: deploy
    if: tag=~/^v\d+\.\d+\.\d+/
  - name: force-deploy
    if: branch=~/^force-deploy/
  - name: nightly-release
    if: (branch=nightly)
